#!/usr/bin/env node
/**
 * scripts/gen-types.mjs — generate packages/core/src/generated/<collection>.ts from
 * schema/<collection>.schema.json via json-schema-to-typescript (T-016, C5).
 *
 * The JSON Schemas are the single source of truth; nothing under packages/ hand-types a
 * schema field list. `pnpm gen:types` writes; `pnpm gen:types --check` exits 1 if any
 * committed output differs from what the schemas would generate now.
 */
import { compile } from "json-schema-to-typescript";
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SCHEMA_DIR = join(ROOT, "schema");
const OUT_DIR = join(ROOT, "packages", "core", "src", "generated");
const CHECK = process.argv.includes("--check");

const BANNER = "/* eslint-disable */\n/**\n * GENERATED by scripts/gen-types.mjs from schema/%s.schema.json — DO NOT EDIT.\n * Run `pnpm gen:types` after changing the schema.\n */";

/** Resolves `kb://<collection>` $refs (incl. self-refs) to the schema file on disk. */
const kbResolver = {
  order: 1,
  canRead: /^kb:\/\//,
  read(file) {
    const name = file.url.replace(/^kb:\/\//, "").replace(/[#/].*$/, "");
    return readFileSync(join(SCHEMA_DIR, `${name}.schema.json`), "utf8");
  },
};

function collections() {
  return readdirSync(SCHEMA_DIR)
    .filter((f) => f.endsWith(".schema.json"))
    .map((f) => f.replace(/\.schema\.json$/, ""))
    .sort();
}

async function generate(collection) {
  const schema = JSON.parse(readFileSync(join(SCHEMA_DIR, `${collection}.schema.json`), "utf8"));
  const ts = await compile(schema, collection, {
    bannerComment: BANNER.replace("%s", collection),
    additionalProperties: true,
    $refOptions: { resolve: { kb: kbResolver } },
    cwd: SCHEMA_DIR,
    style: { printWidth: 100 },
  });
  return ts.replace(/\r\n/g, "\n");
}

/** Domain modules (T-026): every non-test `.ts` file directly under `src/domain/` gets a
 * deterministic re-export line, sorted, so `index.ts` stays 100% generated even though its
 * content now spans two sources (schema/ + domain/) — no hand-edit ever survives `--check`. */
function domainModuleNames(subtree = "domain") {
  const dir = join(ROOT, "packages", "core", "src", subtree);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();
}

export function indexFile(names) {
  const collectionLines = names.map((n) => `export * from "./generated/${n}.js";`);
  const domainLines = domainModuleNames().map((n) => `export * from "./domain/${n}.js";`);
  const body = domainLines.length > 0
    ? `${collectionLines.join("\n")}\n\n${domainLines.join("\n")}\n`
    : `${collectionLines.join("\n")}\n`;
  const alerts = domainModuleNames("alerts").map(n => `export * from "./alerts/${n}.js";`);
  const alertBody = alerts.length ? `\n// U4b/R2 (D-053): the thin alert interface apps/* imports so a real alert can be delivered\n// without apps/* importing packages/meeting-bot (.dependency-cruiser.cjs forbids that edge).\n${alerts.join("\n")}\n` : "";
  return `// @lkb/core — generated types re-exported (schema/ is the source of truth; see scripts/gen-types.mjs).\n// Pure domain functions (no I/O) go in src/domain/<concept>.ts (D-003) — auto re-exported below.\n${body}${alertBody}`;
}

async function main() {
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  const names = collections();
  const expected = new Map();
  for (const name of names) expected.set(join(OUT_DIR, `${name}.ts`), await generate(name));
  expected.set(join(ROOT, "packages", "core", "src", "index.ts"), indexFile(names));

  let drift = 0;
  for (const [path, content] of expected) {
    const current = existsSync(path) ? readFileSync(path, "utf8").replace(/\r\n/g, "\n") : null;
    if (current === content) continue;
    drift += 1;
    if (CHECK) console.error(`DRIFT: ${path.slice(ROOT.length + 1)} does not match schema/`);
    else {
      writeFileSync(path, content, "utf8");
      console.log(`wrote ${path.slice(ROOT.length + 1)}`);
    }
  }
  if (CHECK) {
    if (drift) {
      console.error(`FAIL: ${drift} generated file(s) out of date — run pnpm gen:types`);
      process.exit(1);
    }
    console.log(`OK: ${names.length} generated type file(s) + index.ts match schema/`);
  } else console.log(`done: ${names.length} collection(s), ${drift} file(s) written`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch((e) => {
  console.error(e);
  process.exit(1);
});
